"""Tool Workshop — agents can create, test, and register tools at runtime."""

from __future__ import annotations

import json
import re
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class DraftTool:
    """A tool generated by an agent."""
    id: str = ""
    name: str = ""
    description: str = ""
    code: str = ""
    author_agent_id: str = ""
    status: str = "draft"  # draft → tested → active | failed
    test_result: dict[str, Any] = field(default_factory=dict)
    created_at: float = 0.0
    activated_at: float = 0.0

    def __post_init__(self):
        if not self.id:
            self.id = uuid.uuid4().hex[:12]
        if not self.created_at:
            self.created_at = time.time()


# Safety patterns that are NEVER allowed in generated tools
BLOCKED_PATTERNS = [
    r"\bos\.system\b",
    r"\bsubprocess\b",
    r"\beval\s*\(",
    r"\bexec\s*\(",
    r"\b__import__\b",
    r"\bopen\s*\(.+[\'\"]w",  # file write
    r"\brm\s+-rf",
    r"\bshutil\.rmtree\b",
    r"\bsocket\b",
    r"\burllib\b",
    r"\brequests\b",
]


class ToolWorkshop:
    """Agent-driven tool creation with safety checks."""

    def __init__(self, workshop_dir: Path | str = "data/tool_workshop"):
        self.workshop_dir = Path(workshop_dir)
        self.drafts_dir = self.workshop_dir / "drafts"
        self.active_dir = self.workshop_dir / "active"
        self.failed_dir = self.workshop_dir / "failed"
        self.audit_log = self.workshop_dir / "audit_log.jsonl"

        for d in [self.drafts_dir, self.active_dir, self.failed_dir]:
            d.mkdir(parents=True, exist_ok=True)

    def create_draft(self, name: str, code: str, author_agent_id: str, description: str = "") -> DraftTool:
        """Create a tool draft. Does NOT activate it."""
        draft = DraftTool(
            name=name,
            code=code,
            author_agent_id=author_agent_id,
            description=description,
        )

        # Safety check
        safety_result = self._safety_check(code)
        if not safety_result["safe"]:
            draft.status = "failed"
            draft.test_result = safety_result
            self._save(draft, self.failed_dir)
            self._audit("safety_failed", draft)
            return draft

        # Syntax check
        syntax_result = self._syntax_check(code)
        if not syntax_result["ok"]:
            draft.status = "failed"
            draft.test_result = syntax_result
            self._save(draft, self.failed_dir)
            self._audit("syntax_failed", draft)
            return draft

        # Structure check
        struct_result = self._structure_check(code)
        if not struct_result["ok"]:
            draft.status = "failed"
            draft.test_result = struct_result
            self._save(draft, self.failed_dir)
            self._audit("structure_failed", draft)
            return draft

        self._save(draft, self.drafts_dir)
        self._audit("draft_created", draft)
        return draft

    def test_draft(self, draft_id: str) -> DraftTool | None:
        """Run the tool's self-test in isolation."""
        draft = self._load(draft_id, self.drafts_dir)
        if not draft:
            return None

        try:
            # Execute in isolated namespace
            namespace: dict[str, Any] = {}
            exec(draft.code, namespace)

            if "test" not in namespace:
                draft.status = "failed"
                draft.test_result = {"ok": False, "error": "No test() function found"}
                self._save(draft, self.failed_dir)
                return draft

            result = namespace["test"]()
            if isinstance(result, dict) and result.get("passed"):
                draft.status = "tested"
                draft.test_result = result
                self._save(draft, self.active_dir)  # auto-promote tested → active
                self._audit("test_passed", draft)
            else:
                draft.status = "failed"
                draft.test_result = result if isinstance(result, dict) else {"passed": False, "error": str(result)}
                self._save(draft, self.failed_dir)
                self._audit("test_failed", draft)

        except Exception as e:
            draft.status = "failed"
            draft.test_result = {"passed": False, "error": str(e)}
            self._save(draft, self.failed_dir)
            self._audit("test_exception", draft)

        return draft

    def activate(self, draft_id: str) -> dict[str, Any] | None:
        """Load an active tool and return its run function."""
        draft = self._load(draft_id, self.active_dir)
        if not draft:
            return None

        try:
            namespace: dict[str, Any] = {}
            exec(draft.code, namespace)
            if "run" in namespace:
                return {"run": namespace["run"], "meta": {"name": draft.name, "id": draft.id}}
        except Exception as e:
            return {"error": str(e)}
        return None

    def list_tools(self, status: str | None = None) -> list[dict]:
        tools = []
        for d in [self.drafts_dir, self.active_dir, self.failed_dir]:
            for f in d.glob("*.json"):
                draft = self._load(f.stem, d)
                if draft and (status is None or draft.status == status):
                    tools.append({
                        "id": draft.id, "name": draft.name, "status": draft.status,
                        "author": draft.author_agent_id, "description": draft.description,
                    })
        return tools

    def _safety_check(self, code: str) -> dict:
        for pattern in BLOCKED_PATTERNS:
            if re.search(pattern, code):
                return {"safe": False, "error": f"Blocked pattern: {pattern}"}
        return {"safe": True}

    def _syntax_check(self, code: str) -> dict:
        try:
            compile(code, "<tool>", "exec")
            return {"ok": True}
        except SyntaxError as e:
            return {"ok": False, "error": f"SyntaxError: {e}"}

    def _structure_check(self, code: str) -> dict:
        required = ["def run(", "def test("]
        missing = [r for r in required if r not in code]
        if missing:
            return {"ok": False, "error": f"Missing: {', '.join(missing)}"}
        return {"ok": True}

    def _save(self, draft: DraftTool, directory: Path) -> None:
        path = directory / f"{draft.id}.json"
        path.write_text(json.dumps({
            "id": draft.id, "name": draft.name, "description": draft.description,
            "code": draft.code, "author_agent_id": draft.author_agent_id,
            "status": draft.status, "test_result": draft.test_result,
            "created_at": draft.created_at, "activated_at": draft.activated_at,
        }, ensure_ascii=False, indent=2), encoding="utf-8")

    def _load(self, draft_id: str, directory: Path) -> DraftTool | None:
        path = directory / f"{draft_id}.json"
        if not path.exists():
            return None
        data = json.loads(path.read_text(encoding="utf-8"))
        return DraftTool(**{k: v for k, v in data.items() if k in DraftTool.__dataclass_fields__})

    def _audit(self, event: str, draft: DraftTool) -> None:
        entry = {"ts": time.time(), "event": event, "tool_id": draft.id, "tool_name": draft.name,
                 "author": draft.author_agent_id}
        with open(self.audit_log, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
